#!/usr/bin/env ruby

# source: https://www.atlassian.com/git/tutorials/git-hooks

message_file = ARGV[0]
message = File.read(message_file)

$regex = /\[ref: (\d+)\]/

if !$regex.match(message)
  puts "[POLICY] Your message is not formatted correctly"
  exit 1
end
